version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - QuTech-Delft/web-team
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - QuTech-Delft/web-team
      
