name: Test Python 🐍 package 📦

on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  test:
    name: Test Python 🐍 package 📦
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    runs-on: ${{ matrix.os }}
    env:
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.3.2"
      - name: Install dependencies
        run: poetry install
      - name: Test formatting
        run: poetry run black --check .
      - name: Test sorting
        run: poetry run isort --check .
      - name: Test docstring formatting
        run: poetry run docformatter --check --config ./pyproject.toml .
      - name: Test with pytest
        run: poetry run pytest .
      - name: Static code analysis
        run: poetry run mypy .
      - name: Run pylint
        run: poetry run pylint quantuminspire
